### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Fs02** [michielbdejong/bogor-angkot-gtfs#1]
Hi Michel, Can you let me know the license of this project?
Because currently we are developing a similar navigation app for angkot in Bandung, we've gathered all raw angkot routes in Bandung through service of 3rd party surveyor. I've done pre processing so it's usable in our schema(but unfortunately we don't follow gtfs standard) and ready for custom path finding algorithm.

**Comment by michielbdejong** [comment]
Cool!

You can use all data I entered myself (the manual-from-transitwand folder) under CC-BY-SA, whatevecr the latest version of that is currently.

The data-from-www folder is just that, refer to the individual sources - but I guess there's no problem in you reusing that data - other than the sketchy quality :)

The data-from-kabupaten-office should be open data I guess, it's paid for by Indonesian tax payers and the DLLAJ office is a non-commercial entity, so I don't think you will be sued for making that data available to the people who paid for it :)

**Comment by michielbdejong** [comment]
Why are you not creating a gtfs feed for Bandung? Should be really easy, just export from your own format to the appropriate csv files. Is your data for Bandung publically available?

**Comment by Fs02** [comment]
Wow thanks!!

Yeah, I'm planning to export the data to gtfs format, but we haven't discussed yet either to make the data publically available or not.

**Comment by michielbdejong** [comment]
So are you going to make the Bandung data publically available as well? Please do! :) Closing this issue here now.
