### ISSUE TITLE
What do the symbols in the stop names mean?

### ISSUE THREAD

**Issue by stevevance** [michielbdejong/bogor-angkot-gtfs#15]
Some stops have `*` and `#` preceding a stop name. What do those symbols mean?

**Comment by michielbdejong** [comment]
Ah, sorry! My script generates both a gtfs file and a svg map; these symbols both only have a meaning when drawing http://michielbdejong.com/angkots.svg - `#` means don't display the route numbers at this stop, and `*` means display both route numbers and stop name. I'll update the script to remove them when generating the gtfs.

**Comment by stevevance** [comment]
okay, cool. 
We're working through an issue on why the Transitland isn't recognizing the ZIP file of your repo as a GTFS feed (and our system can dive into the folder hierarchy because your GTFS text files aren't in the root). When we figure that out this feed will be in the [Feed Registry](https://transit.land/feed-registry/).

**Comment by michielbdejong** [comment]
Ah, I probably gave you https://github.com/michielbdejong/bogor-angkot-gtfs/raw/master/release/gtfs.zip as the URL, right? That is served through github 'View raw data', which I found out is served with an incorrect Content-Type of 'text/html' - I copied the file here: http://michielbdejong.com/angkots-gtfs.zip (a gh-pages website) and there it's given `Content-Type: application/zip`, that might help!

**Comment by stevevance** [comment]
I was able to get the feed working by using a `#` directory name filter, so it looks like this: `https://github.com/michielbdejong/bogor-angkot-gtfs/archive/master.zip#bogor-angkot-gtfs-master/gtfs`

However we prefer straight up files so I've switched it to using the new ZIP file you posted. Everything's good now.

**Comment by michielbdejong** [comment]
Great, thanks!

Ah, I didn't know I had pointed you to master.zip,  I couldn't find my submitted details back from your submission-confirmation email, and I thought I had pointed you to  https://github.com/michielbdejong/bogor-angkot-gtfs/raw/master/release/gtfs.zip - sorry.

Anyway, glad it works now! Looking forward to building MapZen apps using this data :)

**Comment by stevevance** [comment]
If the URL changes, you can submit the new one by going to the operator page for this feed, and then clicking the blue "Edit operator and feed details".
